/// <reference types="vitest/config" />
import { fileURLToPath, URL } from 'node:url';
import { defineConfig } from 'vite';
import { VitePWA } from 'vite-plugin-pwa';

// PWA (W3.2): installable, works offline. Icons are generated by scripts/gen-icons.mjs.
export default defineConfig({
  base: './',
  plugins: [
    VitePWA({
      registerType: 'autoUpdate',
      injectRegister: false, // registered from src/main.ts (production only)
      includeAssets: ['icons/favicon-32.png', 'icons/apple-touch-icon.png'],
      manifest: {
        name: 'FREE DEAL TWIN JOKERS (PROG)',
        short_name: 'TWIN JOKERS',
        description: 'A retro arcade video poker: free games, progressive jackpots and three double-down games.',
        start_url: './',
        scope: './',
        display: 'fullscreen',
        orientation: 'any',
        background_color: '#020a05',
        theme_color: '#04140a',
        icons: [
          { src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png' },
          { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png' },
          { src: 'icons/maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,png,webmanifest}'],
        maximumFileSizeToCacheInBytes: 4 * 1024 * 1024,
      },
    }),
  ],
  resolve: { alias: { '@': fileURLToPath(new URL('./src', import.meta.url)) } },
  test: {
    projects: [
      {
        extends: true,
        test: { name: 'unit', include: ['tests/**/*.test.ts'], exclude: ['tests/**/*.slow.test.ts'], environment: 'node' },
      },
      {
        extends: true,
        test: { name: 'slow', include: ['tests/**/*.slow.test.ts'], environment: 'node', testTimeout: 600_000 },
      },
    ],
  },
});
